# Generated by Django 5.1.6 on 2025-03-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0002_comment_likecomment_post_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
