# Generated by Django 4.2.19 on 2025-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0003_item_info_gender_usergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrade',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
