# Generated by Django 5.1.6 on 2025-03-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0004_remove_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='final_project_app.post'),
            preserve_default=False,
        ),
    ]
