# Generated by Django 5.1.6 on 2025-03-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0005_usergrade_grade'),
        ('final_project_app', '0006_comment_post'),
    ]

    operations = [
    ]
