# Generated by Django 5.1.6 on 2025-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0007_merge_0005_usergrade_grade_0006_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTADcCBM2iRy0XhD2lG7FRxBq5jLgvkwTZqWg&s', upload_to=''),
        ),
    ]
