# Generated by Django 5.1.6 on 2025-03-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
